# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state_coordinator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17state_coordinator.proto\x12\x0b\x63oordinator\"S\n\x10HeartBeatRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63urrent_task\x18\x02 \x01(\t\x12\x17\n\x0fload_percentage\x18\x03 \x01(\x02\":\n\x11HeartBeatResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"4\n\x0bLockRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x13\n\x0bresource_id\x18\x02 \x01(\t\"3\n\x0cLockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nlock_token\x18\x02 \x01(\t2\xea\x01\n\x10StateCoordinator\x12N\n\rSendHeartbeat\x12\x1d.coordinator.HeartBeatRequest\x1a\x1e.coordinator.HeartBeatResponse\x12\x42\n\x0b\x41\x63quireLock\x12\x18.coordinator.LockRequest\x1a\x19.coordinator.LockResponse\x12\x42\n\x0bReleaseLock\x12\x18.coordinator.LockRequest\x1a\x19.coordinator.LockResponseB\x16\n\x12\x63om.ai.coordinatorP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_coordinator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.ai.coordinatorP\001'
  _globals['_HEARTBEATREQUEST']._serialized_start=40
  _globals['_HEARTBEATREQUEST']._serialized_end=123
  _globals['_HEARTBEATRESPONSE']._serialized_start=125
  _globals['_HEARTBEATRESPONSE']._serialized_end=183
  _globals['_LOCKREQUEST']._serialized_start=185
  _globals['_LOCKREQUEST']._serialized_end=237
  _globals['_LOCKRESPONSE']._serialized_start=239
  _globals['_LOCKRESPONSE']._serialized_end=290
  _globals['_STATECOORDINATOR']._serialized_start=293
  _globals['_STATECOORDINATOR']._serialized_end=527
# @@protoc_insertion_point(module_scope)
